# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ecegrid/a/ee364j12/S15_Lab10/EntryForm.ui'
#
# Created: Sun Mar 29 20:54:14 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(631, 316)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblFirstName = QtGui.QLabel(self.centralwidget)
        self.lblFirstName.setGeometry(QtCore.QRect(15, 31, 81, 21))
        self.lblFirstName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblFirstName.setObjectName("lblFirstName")
        self.txtFirstName = QtGui.QLineEdit(self.centralwidget)
        self.txtFirstName.setGeometry(QtCore.QRect(105, 31, 201, 20))
        self.txtFirstName.setText("")
        self.txtFirstName.setObjectName("txtFirstName")
        self.txtLastName = QtGui.QLineEdit(self.centralwidget)
        self.txtLastName.setGeometry(QtCore.QRect(405, 31, 201, 20))
        self.txtLastName.setText("")
        self.txtLastName.setObjectName("txtLastName")
        self.lblLastName = QtGui.QLabel(self.centralwidget)
        self.lblLastName.setGeometry(QtCore.QRect(330, 30, 71, 21))
        self.lblLastName.setObjectName("lblLastName")
        self.txtAddress = QtGui.QLineEdit(self.centralwidget)
        self.txtAddress.setGeometry(QtCore.QRect(105, 71, 501, 20))
        self.txtAddress.setText("")
        self.txtAddress.setObjectName("txtAddress")
        self.lblAddress = QtGui.QLabel(self.centralwidget)
        self.lblAddress.setGeometry(QtCore.QRect(25, 71, 71, 21))
        self.lblAddress.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblAddress.setObjectName("lblAddress")
        self.txtCity = QtGui.QLineEdit(self.centralwidget)
        self.txtCity.setGeometry(QtCore.QRect(105, 111, 201, 20))
        self.txtCity.setText("")
        self.txtCity.setObjectName("txtCity")
        self.lblCity = QtGui.QLabel(self.centralwidget)
        self.lblCity.setGeometry(QtCore.QRect(55, 111, 41, 21))
        self.lblCity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCity.setObjectName("lblCity")
        self.lblState = QtGui.QLabel(self.centralwidget)
        self.lblState.setGeometry(QtCore.QRect(355, 111, 41, 21))
        self.lblState.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblState.setObjectName("lblState")
        self.txtState = QtGui.QLineEdit(self.centralwidget)
        self.txtState.setGeometry(QtCore.QRect(405, 111, 41, 20))
        self.txtState.setText("")
        self.txtState.setObjectName("txtState")
        self.txtZip = QtGui.QLineEdit(self.centralwidget)
        self.txtZip.setGeometry(QtCore.QRect(505, 111, 101, 20))
        self.txtZip.setObjectName("txtZip")
        self.lblZip = QtGui.QLabel(self.centralwidget)
        self.lblZip.setGeometry(QtCore.QRect(455, 111, 41, 21))
        self.lblZip.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblZip.setObjectName("lblZip")
        self.txtEmail = QtGui.QLineEdit(self.centralwidget)
        self.txtEmail.setGeometry(QtCore.QRect(105, 151, 501, 20))
        self.txtEmail.setObjectName("txtEmail")
        self.lblEmail = QtGui.QLabel(self.centralwidget)
        self.lblEmail.setGeometry(QtCore.QRect(55, 151, 41, 16))
        self.lblEmail.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblEmail.setObjectName("lblEmail")
        self.btnClear = QtGui.QPushButton(self.centralwidget)
        self.btnClear.setGeometry(QtCore.QRect(103, 240, 75, 23))
        self.btnClear.setObjectName("btnClear")
        self.btnSave = QtGui.QPushButton(self.centralwidget)
        self.btnSave.setEnabled(False)
        self.btnSave.setGeometry(QtCore.QRect(245, 240, 151, 23))
        self.btnSave.setObjectName("btnSave")
        self.btnLoad = QtGui.QPushButton(self.centralwidget)
        self.btnLoad.setGeometry(QtCore.QRect(460, 240, 75, 23))
        self.btnLoad.setObjectName("btnLoad")
        self.lblError = QtGui.QLabel(self.centralwidget)
        self.lblError.setEnabled(True)
        self.lblError.setGeometry(QtCore.QRect(110, 190, 491, 21))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        self.lblError.setFont(font)
        self.lblError.setText("")
        self.lblError.setObjectName("lblError")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 631, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.txtFirstName, self.txtLastName)
        MainWindow.setTabOrder(self.txtLastName, self.txtAddress)
        MainWindow.setTabOrder(self.txtAddress, self.txtCity)
        MainWindow.setTabOrder(self.txtCity, self.txtState)
        MainWindow.setTabOrder(self.txtState, self.txtZip)
        MainWindow.setTabOrder(self.txtZip, self.txtEmail)
        MainWindow.setTabOrder(self.txtEmail, self.btnClear)
        MainWindow.setTabOrder(self.btnClear, self.btnSave)
        MainWindow.setTabOrder(self.btnSave, self.btnLoad)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFirstName.setText(QtGui.QApplication.translate("MainWindow", "First Name", None, QtGui.QApplication.UnicodeUTF8))
        self.lblLastName.setText(QtGui.QApplication.translate("MainWindow", "Last Name", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAddress.setText(QtGui.QApplication.translate("MainWindow", "Address", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCity.setText(QtGui.QApplication.translate("MainWindow", "City", None, QtGui.QApplication.UnicodeUTF8))
        self.lblState.setText(QtGui.QApplication.translate("MainWindow", "State", None, QtGui.QApplication.UnicodeUTF8))
        self.lblZip.setText(QtGui.QApplication.translate("MainWindow", "ZIP", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEmail.setText(QtGui.QApplication.translate("MainWindow", "Email", None, QtGui.QApplication.UnicodeUTF8))
        self.btnClear.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSave.setText(QtGui.QApplication.translate("MainWindow", "Save to \"target.xml\"", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLoad.setText(QtGui.QApplication.translate("MainWindow", "Load ...", None, QtGui.QApplication.UnicodeUTF8))

